server:
  port: 8899

spring:
  redis:
    host: 123.60.150.23
    port: 6379
    password: root@123456
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
      timeout: 3000ms # 连接超时时间（毫秒）

seckill:
  # linux 使用/template/ftl
  templateDir: D:/workspace/tuling/tulingmall-single/doc/template/ftl
  templateName: product.ftl
  # linux 使用/template/html
  htmlDir: D:/workspace/tuling/tulingmall-single/doc/template/html
