server:
  port: 8833
spring:
  application:
    name: tulingmall-unqid
  cloud:
    nacos:
      discovery:
        server-addr: 123.60.150.23:8848
        namespace: ace67433-6b98-4de3-acfe-9eb4b0f059e4
  main:
    allow-bean-definition-overriding: true
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full
#        requestInterceptors:
#          - com.tuling.tulingmall.feignapi.interceptor.HeaderInterceptor
#        readTimeout: 3000
#        connectTimeout: 3000
#logging:
#  level:
#    com:
#      tuling:
#        tulingmall:
#          feignapi:
#            ums:
#              UmsMemberReceiveAddressFeignApi: debug
