spring:
  datasource:
    dynamic:
      primary: user
      # 未匹配到数据源时，true抛异常，false使用默认数据源
      strict: true
      datasource:
        user:
          url: jdbc:mysql://127.0.0.1:3306/tl_mall_user?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        goods:
          url: jdbc:mysql://127.0.0.1:3306/tl_mall_goods?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        promotion:
          url: jdbc:mysql://127.0.0.1:3306/tl_mall_promotion?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        normal:
          url: jdbc:mysql://127.0.0.1:3306/tl_mall_normal?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        order:
          url: jdbc:mysql://127.0.0.1:3306/tl_mall_order?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        cart:
          url: jdbc:mysql://127.0.0.1:3306/tl_mall_cart?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    cluster:
      nodes: 218.76.8.107:8001,218.76.8.107:8002,218.76.8.107:8003
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
      timeout: 3000ms # 连接超时时间（毫秒）