spring:
  datasource:
    url: jdbc:mysql://192.168.65.71:3306/tl_mall_open?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tlmall
    password: tlmall123