spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: tulingmall-authcenter
          uri: lb://tulingmall-authcenter
          predicates:
            - Path=/oauth/**
        - id: tulingmall-member
          uri: lb://tulingmall-member
          predicates:
            - Path=/sso/**,/member/**
        - id: tulingmall-order-curr
          uri: lb://tulingmall-order-curr
          predicates:
            - Path=/order/**
        - id: tulingmall-cart
          uri: lb://tulingmall-cart
          predicates:
            - Path=/cart/**    
        - id: tulingmall-product
          uri: lb://tulingmall-product
          predicates:
            - Path=/pms/**
        - id: tulingmall-promotion
          uri: lb://tulingmall-promotion
          predicates:
            - Path=/coupon/**
        - id: tulingmall-portal
          uri: lb://tulingmall-portal
          predicates:
            - Path=/home/**,/portal/**

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

tuling:
  gateway:
    shouldSkipUrls:
       - /oauth/**
       - /sso/**
       - /home/**
       - /portal/commentlist/**
       - /order/paySuccess/**
       - /pms/**
       - /static/qrcode/**
